# 1. Credenziali e URL del database H2 (in memoria)
spring.datasource.url=jdbc:h2:mem:animedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Comportamento di Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. ABILITA LA CONSOLE WEB DI H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console